bpf: Fix bpf_sockops compilation
Compilation of bpf_sockops from userspace is failing during sockops
tests with the following error:

    /var/lib/cilium/bpf/sockops/bpf_sockops.c:77:10: error: implicit declaration of function 'lookup_ip4_remote_endpoint' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
                    info = lookup_ip4_remote_endpoint(key.dip4);
                           ^
    /var/lib/cilium/bpf/sockops/bpf_sockops.c:77:10: note: did you mean 'lookup_ip4_endpoint'?
    /var/lib/cilium/bpf/lib/eps.h:35:1: note: 'lookup_ip4_endpoint' declared here
    lookup_ip4_endpoint(struct iphdr *ip4)
    ^

Function lookup_ip4_remote_endpoint is undefined because
IPCACHE4_PREFIXES is undefined. IPCACHE4_PREFIXES is defined in the
netdev_config header by userspace. This commit fixes the compilation error
by importing the netdev_config header in bpf_sockops.

Signed-off-by: Paul Chaignon <paul@cilium.io>